version: "3.4"
services:
  frontend:
    container_name: frontend
    image: node:16-bullseye-slim
    working_dir: /home/app
    command: tail -f /dev/null 
    volumes: 
      - ./frontend:/home/app
    ports:
      - 3000:3000
    depends_on:
      - truffle
  truffle:
    container_name: truffle
    build:
      context: .
      target: truffle
    depends_on:
      - ganache
    networks:
      - backend
    volumes:
      - ./backend:/home/app
  ganache:
    container_name: ganache
    command: ganache -p 8545 -h 0.0.0.0
    build:
      context: .
      target: ganache
    ports:
      - 8545:8545
    networks:
      - backend
networks:
  backend:
    driver: "bridge"
